{
 "title": "DB2 pureScale",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network DB2 members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"d[0-1]\",device=\"eth0\"}[5m])",
     "legendFormat": "send {{job}} main"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"d[0-1]\",device=\"eth0\"}[5m])",
     "legendFormat": "receive {{job}} main"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"d[0-1]\",device=\"eth1\"}[5m])",
     "legendFormat": "send {{job}} gfsfe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"d[0-1]\",device=\"eth1\"}[5m])",
     "legendFormat": "receive {{job}} gfsfe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"d[0-1]\",device=\"eth2\"}[5m])",
     "legendFormat": "send {{job}} db2be"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"d[0-1]\",device=\"eth2\"}[5m])",
     "legendFormat": "receive {{job}} db2be"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"d[0-1]\",device=\"eth3\"}[5m])",
     "legendFormat": "send {{job}} db2fe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"d[0-1]\",device=\"eth3\"}[5m])",
     "legendFormat": "receive {{job}} db2fe"
    }
   ]
  },
  {
   "title": "Network DB2 CF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf0\",device=\"eth0\"}[5m])",
     "legendFormat": "send cf0 main"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf0\",device=\"eth0\"}[5m])",
     "legendFormat": "receive cf0 main"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf0\",device=\"eth1\"}[5m])",
     "legendFormat": "send cf0 gfsfe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf0\",device=\"eth1\"}[5m])",
     "legendFormat": "receive cf0 gfsfe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf0\",device=\"eth2\"}[5m])",
     "legendFormat": "send cf0 db2be"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf0\",device=\"eth2\"}[5m])",
     "legendFormat": "receive cf0 db2be"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf0\",device=\"eth3\"}[5m])",
     "legendFormat": "send cf0 db2fe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf0\",device=\"eth3\"}[5m])",
     "legendFormat": "receive cf0 db2fe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf1\",device=\"eth0\"}[5m])",
     "legendFormat": "send cf1 main"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf1\",device=\"eth0\"}[5m])",
     "legendFormat": "receive cf1 main"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf1\",device=\"eth1\"}[5m])",
     "legendFormat": "send cf1 gfsfe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf1\",device=\"eth1\"}[5m])",
     "legendFormat": "receive cf1 gfsfe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf1\",device=\"eth2\"}[5m])",
     "legendFormat": "send cf1 db2be"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf1\",device=\"eth2\"}[5m])",
     "legendFormat": "receive cf1 db2be"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"cf1\",device=\"eth3\"}[5m])",
     "legendFormat": "send cf1 db2fe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"cf1\",device=\"eth3\"}[5m])",
     "legendFormat": "receive cf1 db2fe"
    }
   ]
  },
  {
   "title": "Network Gluster FS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g0\",device=\"eth0\"}[5m])",
     "legendFormat": "send g0 main"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g0\",device=\"eth0\"}[5m])",
     "legendFormat": "receive g0 main"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g0\",device=\"eth1\"}[5m])",
     "legendFormat": "send g0 gfsfe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g0\",device=\"eth1\"}[5m])",
     "legendFormat": "receive g0 gfsfe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g0\",device=\"eth2\"}[5m])",
     "legendFormat": "send g0 db2be"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g0\",device=\"eth2\"}[5m])",
     "legendFormat": "receive g0 db2be"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g0\",device=\"eth3\"}[5m])",
     "legendFormat": "send g0 db2fe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g0\",device=\"eth3\"}[5m])",
     "legendFormat": "receive g0 db2fe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g1\",device=\"eth0\"}[5m])",
     "legendFormat": "send g1 main"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g1\",device=\"eth0\"}[5m])",
     "legendFormat": "receive g1 main"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g1\",device=\"eth1\"}[5m])",
     "legendFormat": "send g1 gfsfe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g1\",device=\"eth1\"}[5m])",
     "legendFormat": "receive g1 gfsfe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g1\",device=\"eth2\"}[5m])",
     "legendFormat": "send g1 db2be"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g1\",device=\"eth2\"}[5m])",
     "legendFormat": "receive g1 db2be"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g1\",device=\"eth3\"}[5m])",
     "legendFormat": "send g1 db2fe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g1\",device=\"eth3\"}[5m])",
     "legendFormat": "receive g1 db2fe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g2\",device=\"eth0\"}[5m])",
     "legendFormat": "send g2 main"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g2\",device=\"eth0\"}[5m])",
     "legendFormat": "receive g2 main"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g2\",device=\"eth1\"}[5m])",
     "legendFormat": "send g2 gfsfe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g2\",device=\"eth1\"}[5m])",
     "legendFormat": "receive g2 gfsfe"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g2\",device=\"eth2\"}[5m])",
     "legendFormat": "send g2 db2be"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g2\",device=\"eth2\"}[5m])",
     "legendFormat": "receive g2 db2be"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"g2\",device=\"eth3\"}[5m])",
     "legendFormat": "send g2 db2fe"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"g2\",device=\"eth3\"}[5m])",
     "legendFormat": "receive g2 db2fe"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"d0\",mode=\"iowait\"}[5m]))",
     "legendFormat": "d0 iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"d0\",mode=\"user\"}[5m]))",
     "legendFormat": "d0 user"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"d1\",mode=\"iowait\"}[5m]))",
     "legendFormat": "d1 iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"d1\",mode=\"user\"}[5m]))",
     "legendFormat": "d1 user"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"cf0\",mode=\"iowait\"}[5m]))",
     "legendFormat": "cf0 iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"cf0\",mode=\"user\"}[5m]))",
     "legendFormat": "cf0 user"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"cf1\",mode=\"iowait\"}[5m]))",
     "legendFormat": "cf1 iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"cf1\",mode=\"user\"}[5m]))",
     "legendFormat": "cf1 user"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"g0\",mode=\"iowait\"}[5m]))",
     "legendFormat": "g0 iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"g0\",mode=\"user\"}[5m]))",
     "legendFormat": "g0 user"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"g1\",mode=\"iowait\"}[5m]))",
     "legendFormat": "d0 iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"g1\",mode=\"user\"}[5m]))",
     "legendFormat": "g1 user"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"g2\",mode=\"iowait\"}[5m]))",
     "legendFormat": "g2 iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"g2\",mode=\"user\"}[5m]))",
     "legendFormat": "g2 user"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"d[0-9]+|g[0-9]+|cf[0-9]+\"}",
     "legendFormat": "mem_avail {{job}}"
    }
   ]
  },
  {
   "title": "IO DB2 members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=~\"d[0-9]*\", device=~\"dm-[0-9]+|db2fs[0-9]+\"}[5m])",
     "legendFormat": "IO-{{job}}-{{device}}"
    }
   ]
  },
  {
   "title": "IO DB2 CF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=~\"cf[0-9]*\", device=~\"dm-[0-9]+|db2fs[0-9]+\"}[5m])",
     "legendFormat": "IO-{{job}}-{{device}}"
    }
   ]
  },
  {
   "title": "IO Gluster FS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=~\"g[0-9]*\", device=~\"dm-[0-9]+|s.*\"}[5m])",
     "legendFormat": "IO-{{job}}-{{device}}"
    }
   ]
  },
  {
   "title": "Reads DB2 members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job='d0',device='dm-0'}[5m])",
     "legendFormat": "reads-d0-dm-0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d0',device='dm-1'}[5m])",
     "legendFormat": "reads-d0-dm-1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d0',device='dm-2'}[5m])",
     "legendFormat": "reads-d0-dm-2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d0',device='dm-3'}[5m])",
     "legendFormat": "reads-d0-dm-3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d0',device='dm-4'}[5m])",
     "legendFormat": "reads-d0-dm-4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d0',device='db2fs1'}[5m])",
     "legendFormat": "reads-d0-db2fs1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d1',device='dm-0'}[5m])",
     "legendFormat": "reads-d1-dm-0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d1',device='dm-1'}[5m])",
     "legendFormat": "reads-d1-dm-1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d1',device='dm-2'}[5m])",
     "legendFormat": "reads-d1-dm-2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d1',device='dm-3'}[5m])",
     "legendFormat": "reads-d1-dm-3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d1',device='dm-4'}[5m])",
     "legendFormat": "reads-d1-dm-4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='d1',device='db2fs1'}[5m])",
     "legendFormat": "reads-d1-db2fs1"
    }
   ]
  },
  {
   "title": "Reads DB2 CF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf0',device='dm-0'}[5m])",
     "legendFormat": "reads-cf0-dm-0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf0',device='dm-1'}[5m])",
     "legendFormat": "reads-cf0-dm-1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf0',device='dm-2'}[5m])",
     "legendFormat": "reads-cf0-dm-2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf0',device='dm-3'}[5m])",
     "legendFormat": "reads-cf0-dm-3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf0',device='dm-4'}[5m])",
     "legendFormat": "reads-cf0-dm-4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf0',device='db2fs1'}[5m])",
     "legendFormat": "reads-cf0-db2fs1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf1',device='dm-0'}[5m])",
     "legendFormat": "reads-cf1-dm-0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf1',device='dm-1'}[5m])",
     "legendFormat": "reads-cf1-dm-1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf1',device='dm-2'}[5m])",
     "legendFormat": "reads-cf1-dm-2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf1',device='dm-3'}[5m])",
     "legendFormat": "reads-cf1-dm-3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf1',device='dm-4'}[5m])",
     "legendFormat": "reads-cf1-dm-4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='cf1',device='db2fs1'}[5m])",
     "legendFormat": "reads-cf1-db2fs1"
    }
   ]
  },
  {
   "title": "Reads Gluster FS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job='g0',device='dm-0'}[5m])",
     "legendFormat": "reads-g0-dm-0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g0',device='sda'}[5m])",
     "legendFormat": "reads-g0-sda"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g0',device='sdb'}[5m])",
     "legendFormat": "reads-g0-sdb"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g0',device='sdc'}[5m])",
     "legendFormat": "reads-g0-sdc"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g0',device='sdd'}[5m])",
     "legendFormat": "reads-g0-sdd"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g0',device='sr0'}[5m])",
     "legendFormat": "reads-g0-sr0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g1',device='dm-0'}[5m])",
     "legendFormat": "reads-g1-dm-0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g1',device='sda'}[5m])",
     "legendFormat": "reads-g1-sda"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g1',device='sdb'}[5m])",
     "legendFormat": "reads-g1-sdb"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g1',device='sdc'}[5m])",
     "legendFormat": "reads-g1-sdc"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g1',device='sdd'}[5m])",
     "legendFormat": "reads-g1-sdd"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g1',device='sr0'}[5m])",
     "legendFormat": "reads-g1-sr0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g2',device='dm-0'}[5m])",
     "legendFormat": "reads-g2-dm-0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g2',device='sda'}[5m])",
     "legendFormat": "reads-g2-sda"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g2',device='sdb'}[5m])",
     "legendFormat": "reads-g2-sdb"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g2',device='sdc'}[5m])",
     "legendFormat": "reads-g2-sdc"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g2',device='sdd'}[5m])",
     "legendFormat": "reads-g2-sdd"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{job='g2',device='sr0'}[5m])",
     "legendFormat": "reads-g2-sr0"
    }
   ]
  },
  {
   "title": "Writes DB2 members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{job='d0',device='dm-0'}[5m])",
     "legendFormat": "writes-d0-dm-0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d0',device='dm-1'}[5m])",
     "legendFormat": "writes-d0-dm-1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d0',device='dm-2'}[5m])",
     "legendFormat": "writes-d0-dm-2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d0',device='dm-3'}[5m])",
     "legendFormat": "writes-d0-dm-3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d0',device='dm-4'}[5m])",
     "legendFormat": "writes-d0-dm-4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d0',device='db2fs1'}[5m])",
     "legendFormat": "writes-d0-db2fs1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d1',device='dm-0'}[5m])",
     "legendFormat": "writes-d1-dm-0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d1',device='dm-1'}[5m])",
     "legendFormat": "writes-d1-dm-1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d1',device='dm-2'}[5m])",
     "legendFormat": "writes-d1-dm-2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d1',device='dm-3'}[5m])",
     "legendFormat": "writes-d1-dm-3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d1',device='dm-4'}[5m])",
     "legendFormat": "writes-d1-dm-4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='d1',device='db2fs1'}[5m])",
     "legendFormat": "writes-d1-db2fs1"
    }
   ]
  },
  {
   "title": "Writes DB2 CF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf0',device='dm-0'}[5m])",
     "legendFormat": "writes-cf0-dm-0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf0',device='dm-1'}[5m])",
     "legendFormat": "writes-cf0-dm-1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf0',device='dm-2'}[5m])",
     "legendFormat": "writes-cf0-dm-2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf0',device='dm-3'}[5m])",
     "legendFormat": "writes-cf0-dm-3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf0',device='dm-4'}[5m])",
     "legendFormat": "writes-cf0-dm-4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf0',device='db2fs1'}[5m])",
     "legendFormat": "writes-cf0-db2fs1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf1',device='dm-0'}[5m])",
     "legendFormat": "writes-cf1-dm-0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf1',device='dm-1'}[5m])",
     "legendFormat": "writes-cf1-dm-1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf1',device='dm-2'}[5m])",
     "legendFormat": "writes-cf1-dm-2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf1',device='dm-3'}[5m])",
     "legendFormat": "writes-cf1-dm-3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf1',device='dm-4'}[5m])",
     "legendFormat": "writes-cf1-dm-4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='cf1',device='db2fs1'}[5m])",
     "legendFormat": "writes-cf1-db2fs1"
    }
   ]
  },
  {
   "title": "Writes Gluster FS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{job='g0',device='dm-0'}[5m])",
     "legendFormat": "writes-g0-dm-0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g0',device='sda'}[5m])",
     "legendFormat": "writes-g0-sda"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g0',device='sdb'}[5m])",
     "legendFormat": "writes-g0-sdb"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g0',device='sdc'}[5m])",
     "legendFormat": "writes-g0-sdc"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g0',device='sdd'}[5m])",
     "legendFormat": "writes-g0-sdd"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g0',device='sr0'}[5m])",
     "legendFormat": "writes-g0-sr0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g1',device='dm-0'}[5m])",
     "legendFormat": "writes-g1-dm-0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g1',device='sda'}[5m])",
     "legendFormat": "writes-g1-sda"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g1',device='sdb'}[5m])",
     "legendFormat": "writes-g1-sdb"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g1',device='sdc'}[5m])",
     "legendFormat": "writes-g1-sdc"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g1',device='sdd'}[5m])",
     "legendFormat": "writes-g1-sdd"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g1',device='sr0'}[5m])",
     "legendFormat": "writes-g1-sr0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g2',device='dm-0'}[5m])",
     "legendFormat": "writes-g2-dm-0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g2',device='sda'}[5m])",
     "legendFormat": "writes-g2-sda"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g2',device='sdb'}[5m])",
     "legendFormat": "writes-g2-sdb"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g2',device='sdc'}[5m])",
     "legendFormat": "writes-g2-sdc"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g2',device='sdd'}[5m])",
     "legendFormat": "writes-g2-sdd"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job='g2',device='sr0'}[5m])",
     "legendFormat": "writes-g2-sr0"
    }
   ]
  }
 ]
}