{
 "title": "d180416",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "disk reads db2vm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_reads_completed_total{device=\"sdd\", instance=\"db2vm:9100\", job=\"db2vm\"}"
    },
    {
     "expr": "node_disk_reads_completed_total{device=\"sdh\", instance=\"db2vm:9100\", job=\"db2vm\"}"
    },
    {
     "expr": "node_disk_reads_completed_total{device=\"sdl\", instance=\"db2vm:9100\", job=\"db2vm\"}"
    }
   ]
  },
  {
   "title": "disk writes db2vm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_writes_completed_total{device=\"sdd\", instance=\"db2vm:9100\", job=\"db2vm\"}"
    },
    {
     "expr": "node_disk_writes_completed_total{device=\"sdh\", instance=\"db2vm:9100\", job=\"db2vm\"}"
    },
    {
     "expr": "node_disk_writes_completed_total{device=\"sdl\", instance=\"db2vm:9100\", job=\"db2vm\"}"
    }
   ]
  },
  {
   "title": "disk reads GlusterFS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_reads_completed_total{device=\"sdc\", instance=\"g1:9100\", job=\"g1\"}"
    },
    {
     "expr": "node_disk_reads_completed_total{device=\"sdd\", instance=\"g1:9100\", job=\"g1\"}"
    },
    {
     "expr": "node_disk_reads_completed_total{device=\"sdc\", instance=\"g2:9100\", job=\"g2\"}"
    },
    {
     "expr": "node_disk_reads_completed_total{device=\"sdd\", instance=\"g2:9100\", job=\"g2\"}"
    },
    {
     "expr": "node_disk_reads_completed_total{device=\"sdc\", instance=\"g3:9100\", job=\"g3\"}"
    },
    {
     "expr": "node_disk_reads_completed_total{device=\"sdd\", instance=\"g3:9100\", job=\"g3\"}"
    }
   ]
  },
  {
   "title": "disk writes GlusterFS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_writes_completed_total{device=\"sdc\", instance=\"g1:9100\", job=\"g1\"}"
    },
    {
     "expr": "node_disk_writes_completed_total{device=\"sdd\", instance=\"g1:9100\", job=\"g1\"}"
    },
    {
     "expr": "node_disk_writes_completed_total{device=\"sdc\", instance=\"g2:9100\", job=\"g2\"}"
    },
    {
     "expr": "node_disk_writes_completed_total{device=\"sdd\", instance=\"g2:9100\", job=\"g2\"}"
    },
    {
     "expr": "node_disk_writes_completed_total{device=\"sdc\", instance=\"g3:9100\", job=\"g3\"}"
    },
    {
     "expr": "node_disk_writes_completed_total{device=\"sdd\", instance=\"g3:9100\", job=\"g3\"}"
    }
   ]
  }
 ]
}