{
 "title": "DB2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"db2vm\",device=\"eth0\"}[5m])",
     "legendFormat": "send"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"db2vm\",device=\"eth0\"}[5m])",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "Disk latency DB2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='db2vm',device='sdh'}[5m])",
     "legendFormat": "mpatha-g1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='db2vm',device='sdl'}[5m])",
     "legendFormat": "mpatha-g2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='db2vm',device='sdd'}[5m])",
     "legendFormat": "mpatha-g3"
    }
   ]
  },
  {
   "title": "Disk latency gluster nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='g1',device='sdc'}[5m])",
     "legendFormat": "latency_g1-disk1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='g1',device='sdd'}[5m])",
     "legendFormat": "latency_g1-disk2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='g2',device='sdc'}[5m])",
     "legendFormat": "latency_g2-disk1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='g2',device='sdd'}[5m])",
     "legendFormat": "latency_g2-disk2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='g3',device='sdc'}[5m])",
     "legendFormat": "latency_g3-disk1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='g3',device='sdd'}[5m])",
     "legendFormat": "latency_g3-disk2"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{job='db2vm',device='dm-0'}",
     "legendFormat": "iops_dm0"
    },
    {
     "expr": "node_disk_io_now{job='db2vm',device='sdh'}",
     "legendFormat": "iops_g1"
    },
    {
     "expr": "node_disk_io_now{job='db2vm',device='sdl'}",
     "legendFormat": "iops_g2"
    },
    {
     "expr": "node_disk_io_now{job='db2vm',device='sdd'}",
     "legendFormat": "iops_g3"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"db2vm\"}",
     "legendFormat": "mem_avail"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"db2vm\",mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"db2vm\",mode=\"idle\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"db2vm\",mode=\"user\"}[5m]))",
     "legendFormat": "user"
    }
   ]
  }
 ]
}