global:
  scrape_interval:     5s
  evaluation_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'd0'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.20:9100']
  - job_name: 'd1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.21:9100']
  - job_name: 'cf0'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.30:9100']
  - job_name: 'cf1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.31:9100']
  - job_name: 'g0'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.10:9100']
  - job_name: 'g1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.11:9100']
  - job_name: 'g2'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.12:9100']
